#!/bin/sh
echo "Is it morning? Please answer yes or no"
read timeofday

case "$timeofday" in
	[yY] | [Yy][Ee][Ss]) echo "Good Morning";;
	[nN]*) echo "Good Afternoon";;
	*) echo "Sorry, answer not recognized";;
esac
exit 0
